eureka:
    client:
        healthcheck:
            enabled: true
        lease:
            duration: 5
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/
    instance:
        leaseExpirationDurationInSeconds: 5
        leaseRenewalIntervalInSeconds: 1
server:
    port: 8080
spring:
    application:
        name: gateway-service